#!/usr/bin/env lua
local args={...}
local code=table.concat(args, ' ')
local load=loadstring or load
for k, v in pairs(math) do
	if not _G[k] then
		_G[k]=v
	end
end
code=[[
return (function()
	return (]]..(code~='' and code or '0')..[[)
end)()]]
local fn, err=load(code)
if fn then
	print(fn())
else
	print('Err:', err)
end
