#!/usr/bin/env lua

-- read arguments
local args={...}
local code=table.concat(args, ' ')
if code=='-' then
	code=io.read '*a'
elseif code=='' then
	io.write '0\n'
	os.exit(0)
end

-- expose the math lib
setmetatable(_G, {__index=math})

-- compatibility with lua5.1
load=loadstring or load
if _VERSION<'Lua 5.2' then
	local ln=math.log
	function log(a, b)
		if not b then
			return ln(a)
		end
		return ln(a)/ln(b)
	end
end

-- useful math functions
function pow(a, b)
	return a^b
end
function log2(a)
	return log(a, 2)
end
function log10(a)
	return log(a, 10)
end
ln=log

-- useful math constants
e=exp(1)
inf=huge

-- execute the code
code=[[return (]]..code..[[)]]
io.write(load(code)())
io.write '\n'
