#!/usr/bin/env lua

local arg={...}
local n=tonumber(arg[1])

if not n then
	io.stderr:write "Usage: rep <n> [text]\n"
	io.stderr:write "\tn:\tNumber of times to repeat the input text\n"
	io.stderr:write "\ttext:\tThe text to repeat, read from stdin if not given\n"
	os.exit(1)
end

local t=arg[2] or io.stdin:read '*a'

for i=1, n do
	io.write(t)
end

